### ISSUE TITLE
Optimizing games

### ISSUE THREAD

**Issue by Kirbymain001** [Bytestorm5/Buckshot-Roulette-Python#2]
Hello, this might be a dumb question, how do i use this to help optimize my games, im not all that experienced in coding so i'm just kinda stuck.

**Comment by Bytestorm5** [comment]
There's a variety of approaches- you could put together an interface just to practice playing without the animations, but really what I've been doing is developing algorithms to play the game for me, and in doing so I get a lot of insight for optimal strategies and the like. Really depends on your skill and what you want to do but yeah

**Comment by Kirbymain001** [comment]
yeah, im looking for a way to make a algorithm that can play the game for me.

**Comment by Bytestorm5** [comment]
Gotcha- I usually follow a format like this:
```python
class Model:
    def __init__(self, playing_as: Literal[0, 1]):
        self.me = playing_as
    
    def choice(self, board: BuckshotRoulette) -> str:
        # Determine what move to make from the current position
        items = board.items[self.me]
        ...
    
    def post(self, last_move, move_result):
        # Processing the result of a given action
        # Usually storing the result of magnifying glass or burner phone
        ...
```

From there once you implement whatever logic you want to test, you can apply whatever optimization/evaluation method you want to use in order to see how you can improve from there. What I used to do before the update is run 1000 trials of my test model against the Dealer. Right now the dealer code is hot garbage (my fault, I'll get to it) so I wouldn't do that right now tho.

I guess I should probably clarify, the purpose of this package isn't to do any optimization itself if that's what you were expecting. It's just intended to be a reliable mockup of the game that you can use, and save some time worrying if the actual game representation is broken rather than the model.
